plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

sourceCompatibility = JavaVersion.toVersion(project.java_version)
targetCompatibility = JavaVersion.toVersion(project.java_version)

version = project.mod_version
group = project.maven_group

repositories {
    maven { name = 'BlueMap'; url = 'https://repo.bluecolored.de/releases' }
    maven { name = 'JourneyMap'; url = 'https://jm.gserv.me/repository/maven-public/' }
    maven { name = 'JourneyMap2'; url = 'https://maven.blamejared.com' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // BlueMap API (compileOnly)
    compileOnly "de.bluecolored:bluemap-api:${project.bluemap_api_version}"

    // JourneyMap API (compileOnly)
    compileOnly "info.journeymap:journeymap-api-fabric:${project.journeymap_api_version}"

    // SnakeYAML
    modImplementation "org.yaml:snakeyaml:${project.snakeyaml_version}"
    include "org.yaml:snakeyaml:${project.snakeyaml_version}"

    // JDBC drivers
    include implementation("com.zaxxer:HikariCP:5.1.0")
    include implementation("com.mysql:mysql-connector-j:8.3.0")
    include implementation("org.xerial:sqlite-jdbc:3.45.1.0")
    include implementation("com.h2database:h2:2.2.224")
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_depends", ">=1.20.5"
    inputs.property "fabricloader_depends", ">=0.15.0"
    inputs.property "fabricapi_depends", ">=0.92.0"

    filesMatching("fabric.mod.json") {
        expand(
            "version": project.version,
            "minecraft_depends": ">=1.20.5",
            "fabricloader_depends": ">=0.15.0",
            "fabricapi_depends": ">=0.92.0"
        )
    }
}

tasks.withType(JavaCompile) { options.encoding = "UTF-8" }

remapJar {
    archiveFileName = "map-chameleon-${project.mod_version}+mc1.20.5-1.21.jar"
}
jar { from "LICENSE" }
